on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_call: {}

name: Test

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Add mask for secrets
        run: |
          echo "::add-mask::${{ secrets.NPCAP_URL }}"

      - uses: actions/checkout@v5
      - name: Install Windows tools
        run: |
          .\.github\InstallShims.ps1
          .\.github\InstallDrivers.ps1
        if: matrix.os == 'windows-latest'
        env:
          NPCAP_URL: ${{ secrets.NPCAP_URL }}

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install required Python packages
        run: pip install -r requirements.txt

      - name: Build local binaries
        run: python ./build.py --architectures local --platforms local

      - name: Run tests
        run: |
          sudo -H -E -- "$(which pytest)" --reruns 3 --reruns-delay 1 -p no:cacheprovider ./tests
