on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_call: {}

name: Test

jobs:
  test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Add mask for secrets
        if: matrix.os == 'windows-latest'
        run: |
          echo "::add-mask::${{ secrets.NPCAP_URL }}"
      - name: Install drivers
        run: .\.github\InstallDrivers.ps1
        if: matrix.os == 'windows-latest'
        env:
          NPCAP_URL: ${{ secrets.NPCAP_URL }}

      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install required Python packages
        run: pip install -r requirements.txt

      - name: Build local binaries
        run: ./build.py --architecture local --platform local

      - name: Run tests
        run: sudo -H -E "$(which pytest)" --reruns 3 --reruns-delay 1 -p no:cacheprovider ./tests
        if: matrix.os != 'windows-latest'
      - name: Run tests
        run: pytest --reruns 3 --reruns-delay 1 -p no:cacheprovider ./tests
        if: matrix.os == 'windows-latest'
